<a href="https://colab.research.google.com/github/maggiejohnson20/DataProcessingAndVisualization/blob/main/Quiz17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Let's begin by grabbing the data frame.

In [1]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/nurfnick/Data_Viz/main/iris.csv')
df

     SepalLength  SepalWidth  PedalLength  PedalWidth           Class
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

Lets try to see if we can find the mean, median, count and sd if we group by class.

In [3]:
df.groupby('Class').SepalLength.agg(['mean','median','count', 'std'])

                  mean  median  count       std
Class
Iris-setosa      5.006     5.0     50  0.352490
Iris-versicolor  5.936     5.9     50  0.516171
Iris-virginica   6.588     6.5     50  0.635880